server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: Currency Fetcher
    version: 0.0.1
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: fetcher
    open-in-view: false
  liquibase:
    default-schema: fetcher
    change-log: classpath:db/liquibase-changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
  cloud:
    openfeign:
      client:
        config:
          binance:
            url: ${BINANCE_URL}
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
logging:
  level:
    com.pdp.currencyfetcher: ${LOG_LEVEL}
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always