server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: currency-fetcher
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: fetcher
    open-in-view: false
  liquibase:
    default-schema: fetcher
    change-log: classpath:db/liquibase-changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
